#!/usr/bin/env python3
"""
Equation Solver — Build Report Generator
=========================================

Parse build logs và tạo markdown summary report.
Dùng cho CI pipeline — hiển thị thông tin build trên GitHub/Jenkins.

Usage:
    python scripts/generate_report.py
    python scripts/generate_report.py --build-log build/build.log --output build-report.md
"""

import argparse
import re
import sys
from datetime import datetime
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent


def count_source_lines(filepath: Path) -> int:
    """Đếm số dòng code trong file."""
    if not filepath.exists():
        return 0
    try:
        return sum(1 for _ in filepath.open(encoding="utf-8", errors="ignore"))
    except Exception:
        return 0


def parse_build_log(log_path: Path) -> dict:
    """Parse ESP-IDF build log."""
    info = {
        "exists": log_path.exists(),
        "errors": 0,
        "warnings": 0,
        "success": False,
    }
    if not log_path.exists():
        return info

    content = log_path.read_text(encoding="utf-8", errors="ignore")
    for line in content.splitlines():
        if re.search(r":\d+:\d+: error:", line):
            info["errors"] += 1
        if re.search(r":\d+:\d+: warning:", line):
            info["warnings"] += 1
        if "Project build complete" in line or "Successfully" in line:
            info["success"] = True

    if info["errors"] == 0:
        info["success"] = True
    return info


def generate_report(build_info: dict, output_path: Path):
    """Generate markdown report."""
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    c_lines = count_source_lines(PROJECT_ROOT / "main" / "root32.c")
    py_lines = count_source_lines(PROJECT_ROOT / "raspi" / "rootpi.py")

    status = "✅ SUCCESS" if build_info["success"] else "❌ FAILED"

    report = f"""# 🔢 Equation Solver — Build Report

**Generated:** {now}
**Status:** {status}

---

## 📊 Build Summary

| Metric | Value |
|--------|-------|
| Build Status | {status} |
| Errors | {build_info["errors"]} |
| Warnings | {build_info["warnings"]} |

## 📏 Codebase

| File | Language | Lines |
|------|----------|-------|
| `main/root32.c` | C (ESP-IDF/FreeRTOS) | {c_lines} |
| `raspi/rootpi.py` | Python | {py_lines} |
| **Total** | | **{c_lines + py_lines}** |

## 🛠 Build Toolchain

- **Compiler:** xtensa-esp32-elf-gcc (via ESP-IDF)
- **Build System:** CMake → Make → gcc
- **Framework:** ESP-IDF v5.1 + FreeRTOS
- **CI:** GitHub Actions

---
*Report generated by `scripts/generate_report.py`*
"""

    output_path.write_text(report, encoding="utf-8")
    print(f"📄 Build report saved to: {output_path}")


def main():
    parser = argparse.ArgumentParser(description="Build Report Generator")
    parser.add_argument(
        "--build-log", type=Path,
        default=PROJECT_ROOT / "build" / "build.log",
        help="Path to build log",
    )
    parser.add_argument(
        "--output", type=Path,
        default=PROJECT_ROOT / "build-report.md",
        help="Output report path",
    )
    args = parser.parse_args()

    print("=" * 50)
    print(" Equation Solver — Build Report Generator")
    print("=" * 50)

    build_info = parse_build_log(args.build_log)
    generate_report(build_info, args.output)


if __name__ == "__main__":
    main()
